### ISSUE TITLE
Upgrade JBoss Class File Writer to 1.3.0.Final

### ISSUE THREAD

**Issue by ropalka** [jbossas/jboss-invocation#41]
With this upgrade it will be possible to build, compile and run JBoss Invocation test suite on JDK12 and above. 
Without this upgrade [WFLY-11406](https://issues.redhat.com/browse/WFLY-11406) will pop up.

**Comment by chengfang** [comment]
diff: https://github.com/jbossas/jboss-classfilewriter/compare/1.2.5.Final...1.3.0.Final
