### ISSUE TITLE
Upgrade github actions to avoid github action warnings

### ISSUE THREAD

**Issue by chengfang** [jbossas/jboss-invocation#51]
There are warnings in github actions summary page:

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, AdoptOpenJDK/install-jdk@v1

We should upgrade to the following actions:

actions/checkout@v3: https://github.com/actions/checkout

actions/setup-java@v3: https://github.com/actions/setup-java

actions/upload-artifact@v3: https://github.com/actions/upload-artifact

**Comment by ropalka** [comment]
Thanks for reporting this @chengfang !
